### ISSUE TITLE
Add instructions to compress images

### ISSUE THREAD

**Issue by agarrharr** [agarrharr/awesome-macos-screensavers#22]
We should compress images (like @bfarayev did in #21). Add instructions to `contributing.md`.

It would be nice if it could be done with a command line tool. If not, add instructions to use a tool like [ImageOptim](https://imageoptim.com/command-line.html).

**Comment by mischah** [comment]
There is a [ImageOptim CLI](https://github.com/JamieMason/ImageOptim-CLI#installation) which needs to be installed via Homebrew.

So I guess the best thing would be to recommend an online webapp like:
- https://compressor.io/compress
- https://kraken.io/web-interface
- https://www.iloveimg.com/compress-image

What do you think?

**Comment by agarrharr** [comment]
There's also ImageMagick. I'd be open to a PR suggesting any of these things.

**Comment by agarrharr** [comment]
By the way, I have this alias for resizing/optimizing for the web:

```sh
# $1 input_image
# $2 width
# $3 output_dir
# https://www.smashingmagazine.com/2015/06/efficient-image-resizing-with-imagemagick/
smartresize() {
   mogrify -path $3 -filter Triangle -define filter:support=2 -thumbnail $2 -unsharp 0.25x0.08+8.3+0.045 -dither None -posterize 136 -quality 82 -define jpeg:fancy-upsampling=off -define png:compression-filter=5 -define png:compression-level=9 -define png:compression-strategy=1 -define png:exclude-chunk=all -interlace none -colorspace sRGB $1
}
```
