### ISSUE TITLE
Allow images wider than 1000px

### ISSUE THREAD

**Issue by Wandmalfarbe** [agarrharr/awesome-macos-screensavers#37]
It would be nice to allow the upload of images wider than 1000px. All the screensaver images are currently blurry on my retina display. The different widths are no problem in the readme because github automatically scales the images to 100% width.

To be perfectly crisp, each image has to have a width of at least 1796px (or more). You can measure this for yourself in the screenshot below.

<img width="1105" alt="screenshot 2018-08-11 00 43 38" src="https://user-images.githubusercontent.com/17237627/43984327-217a9470-9d00-11e8-9510-94feb3613de7.png">

**Comment by agarrharr** [comment]
Good point. I'm on a retina 13" and I haven't noticed. Perhaps, you could submit a PR to update the `contributing.md` file where it says to use the command `sips -Z 1000 ~/Desktop/screenshots/*.png`.
