### ISSUE TITLE
Add Brooklyn to the list

### ISSUE THREAD

**Issue by mischah** [agarrharr/awesome-macos-screensavers#45]
Hej,

is [Brooklyn](https://github.com/pedrommcarrasco/Brooklyn) a screensaver you’d like to have in this list?

If so:
What is the appropriate category?
Graphics?

**Comment by agarrharr** [comment]
Definitely! That is awesome!

Probably should change "iOS (and Apple TV) Inspired" to "Apple Inspired". Then I should also move the "October 30" screensaver up next to this one.
