### ISSUE TITLE
The Johansson deisgn collection has been removed from his webpage

### ISSUE THREAD

**Issue by TheElectroclassics** [agarrharr/awesome-macos-screensavers#67]
It returns a 404 error.

RIP.

**Comment by agarrharr** [comment]
It looks like they are on the projects page now. https://johansson.design/projects/

**Comment by alex-628** [comment]
Nevermind, looks like the website now redirects to some weird Russian gambling site I guess. Only one screensaver was even archived in the Wayback machine :/
